theme: jekyll-theme-hacker

title: Group 6 Terminal Assessment - OOP

description:
This website was created to document the automated payroll system our group has created for MotorPH. Designed to streamline the company's payroll processes, enhance accuracy and efficiency, our system caters to the MotorPH's employees, HR Department, IT Department, and Finance Department.

## GROUP INFORMATION                           

Section: A2101                                                                                                                     
Group No:  6                                                                                                                      
Members: Felicity Diana Sario, Marjorie Navarro
